#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android.Yorsh.Resource", IsApplication=true)]

namespace Android.Yorsh
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Android.Yorsh.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Android.Yorsh.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050007
			public const int AndSuddenly = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Bear = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int HowToPlay = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int MakeThis = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Refuse = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int RefuseAndMove = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int RulesCirle = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ShortAboutGame = 2131034117;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060007
			public const int black = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int bonus_bg = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int bonus_blue = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int bonus_green = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int button_disabled = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int button_shadow_gray = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int button_shadow_gray_text = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int button_text_disabled = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int name_black = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int position_gray = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int pressed_text_color = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int task_progress_bg = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int task_progress_black = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int task_progress_green = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int task_progress_red = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int tournament_green = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int white = 2131099656;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070002
			public const int ActionBar_Size = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ActionBar_TitleMargin = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int ActionBar_TitleSize = 2131165185;
			
			// aapt resource value: 0x7f070020
			public const int AddNewPlayers_buttonHeight = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int AddNewPlayers_buttonTextSize = 2131165214;
			
			// aapt resource value: 0x7f070021
			public const int AddNewPlayers_buttonWidth = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int AddNewPlayers_editTextPadding = 2131165219;
			
			// aapt resource value: 0x7f07001d
			public const int AddNewPlayers_editTextSize = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int AddNewPlayers_imageSize = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int AddNewPlayers_padding = 2131165218;
			
			// aapt resource value: 0x7f070019
			public const int AddPlayerItem_imageSize = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int AddPlayerItem_isPlayTextSize = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int AddPlayerItem_marginLeft = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int AddPlayerItem_marginRight = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int AddPlayerItem_nameTextSize = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int AddPlayerItem_paddingBottom = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int AddPlayerItem_paddingTop = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int AddPlayerItem_removeLayoutSize = 2131165210;
			
			// aapt resource value: 0x7f070044
			public const int Bonus_BonusNameTextSize = 2131165252;
			
			// aapt resource value: 0x7f070043
			public const int Bonus_BonusNameTextWidth = 2131165251;
			
			// aapt resource value: 0x7f070046
			public const int Bonus_ButtonHeight = 2131165254;
			
			// aapt resource value: 0x7f070045
			public const int Bonus_ButtonWidth = 2131165253;
			
			// aapt resource value: 0x7f070041
			public const int Bonus_CongratsTextSize = 2131165249;
			
			// aapt resource value: 0x7f07003d
			public const int Bonus_ContentPadding = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int Bonus_ImageHeight = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int Bonus_ImageWidth = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int Bonus_MarginBottom = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int Bonus_YouWonBonusTextSize = 2131165250;
			
			// aapt resource value: 0x7f070005
			public const int ContentMarginLeftRight = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int ContentMarginTopBottom = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int Dialog_MinWidth = 2131165188;
			
			// aapt resource value: 0x7f070051
			public const int FirstPalyerItem_HalfImageSize = 2131165265;
			
			// aapt resource value: 0x7f070050
			public const int FirstPlayerItem_ImageSize = 2131165264;
			
			// aapt resource value: 0x7f070035
			public const int Game_BottomButtonHeight = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int Game_BottomButtonLeftRightMargin = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int Game_BottomButtonTextSize = 2131165239;
			
			// aapt resource value: 0x7f070034
			public const int Game_BottomButtonWidth = 2131165236;
			
			// aapt resource value: 0x7f070032
			public const int Game_CardButtonHeight = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int Game_CardButtonWidth = 2131165235;
			
			// aapt resource value: 0x7f070028
			public const int Game_ContentPaddingLeftRight = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int Game_ContentPaddingTopBottom = 2131165225;
			
			// aapt resource value: 0x7f070038
			public const int Game_PointsLayoutHeight = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int Game_PointsSize = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int Game_PointsTextSize = 2131165242;
			
			// aapt resource value: 0x7f07002d
			public const int Game_TopBarCountScoreTextSize = 2131165229;
			
			// aapt resource value: 0x7f07002a
			public const int Game_TopBarHeight = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int Game_TopBarImageSize = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int Game_TopBarMargin = 2131165228;
			
			// aapt resource value: 0x7f070030
			public const int Game_TopBarPlayerNameTextSize = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int Game_TopBarPlayerPositionTextSize = 2131165233;
			
			// aapt resource value: 0x7f07002e
			public const int Game_TopBarScoreTextSize = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int Game_TopBarTextMargin = 2131165231;
			
			// aapt resource value: 0x7f07003b
			public const int Game_x2Size = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int Game_x2TextSize = 2131165244;
			
			// aapt resource value: 0x7f070024
			public const int ImageCard_MarginBottom = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int ImageCard_TextHeight = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int ImageCard_TextPadding = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int ImageCard_TextSize = 2131165221;
			
			// aapt resource value: 0x7f07000a
			public const int MainMenu_linkMarginBottom = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int MainMenu_linkMarginTop = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int MainMenu_linkSize = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int MainMenu_logoSize = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int MainMenu_plusTaskButtonHeight = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int MainMenu_plusTaskButtonTextSize = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int MainMenu_plusTaskButtonWidth = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int MainMenu_startButtonHeight = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int MainMenu_startButtonMarginBottom = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int MainMenu_startButtonTextSize = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int MainMenu_startButtonWidth = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int PlayersList_buttonHeight = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int PlayersList_buttonTextSize = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int PlayersList_buttonWidth = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int RoundedCorners = 2131165184;
			
			// aapt resource value: 0x7f07005a
			public const int RuleFragment_ContainerTextSize = 2131165274;
			
			// aapt resource value: 0x7f070059
			public const int RuleFragment_HeaderTextMarginTopBottom = 2131165273;
			
			// aapt resource value: 0x7f070058
			public const int RuleFragment_HeaderTextSize = 2131165272;
			
			// aapt resource value: 0x7f070057
			public const int RuleFragment_ImageViewHeight = 2131165271;
			
			// aapt resource value: 0x7f070053
			public const int RuleFragment_LayoutMarginBottom = 2131165267;
			
			// aapt resource value: 0x7f070055
			public const int RuleFragment_LayoutMarginLeftRight = 2131165269;
			
			// aapt resource value: 0x7f070054
			public const int RuleFragment_LayoutMarginTop = 2131165268;
			
			// aapt resource value: 0x7f070056
			public const int RuleFragment_LayoutPadding = 2131165270;
			
			// aapt resource value: 0x7f070052
			public const int RuleFragment_ScrollImageMarginBottom = 2131165266;
			
			// aapt resource value: 0x7f07004b
			public const int TaskProgress_ContinueButtonHeight = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int TaskProgress_ContinueButtonWidth = 2131165260;
			
			// aapt resource value: 0x7f07004e
			public const int TaskProgress_CurrentScoreTextSize = 2131165262;
			
			// aapt resource value: 0x7f07004a
			public const int TaskProgress_DescTextSize = 2131165258;
			
			// aapt resource value: 0x7f07004f
			public const int TaskProgress_EndDescTextSize = 2131165263;
			
			// aapt resource value: 0x7f070048
			public const int TaskProgress_MarginBottom = 2131165256;
			
			// aapt resource value: 0x7f070047
			public const int TaskProgress_MarginTop = 2131165255;
			
			// aapt resource value: 0x7f07004d
			public const int TaskProgress_ScoreLayoutHeight = 2131165261;
			
			// aapt resource value: 0x7f070049
			public const int TaskProgress_TitleTextSize = 2131165257;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_new_player = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_player_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add_player_button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int add_player_button_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back_button_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int back_button_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int beer_icon_adblock = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_shop = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bonus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bonus_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bonus_button_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cancel_button = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int card_backside = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int choose_from_contacts = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int circle_shape = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int confety = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int continue_button = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int continue_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int delete_button = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int done = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int first_player = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int game_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int home_button = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon_center_all = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon_top_70 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int iq_bg = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int light_bottom = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int light_top = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int logo = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int photo_default = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int plus_tasks_button = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int points = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ready_button = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ready_label_enable = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int rgb_star = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int round_rect_shape_grey_background = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int round_rect_shape_white_background = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int round_rect_shape_white_border = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int rules_button = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int rules_one_page = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int rules_one_sroll_page = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int rules_three_page = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int rules_three_sroll_page = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int rules_two_page = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int rules_two_sroll_page = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int sale_20 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int shadow = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int shared = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int splash = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int splash_screen = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int star_1_copy_2_star_1_copy_3_20_copy = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int start_game_button = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int start_new_game_button = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int table_button = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int table_list_background = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int taskprogress_background = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int x2 = 2130837563;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090024
			public const int BoardGame = 2131296292;
			
			// aapt resource value: 0x7f090027
			public const int PlusCards = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int Rules = 2131296294;
			
			// aapt resource value: 0x7f090025
			public const int StartGame = 2131296293;
			
			// aapt resource value: 0x7f090004
			public const int TextView01 = 2131296260;
			
			// aapt resource value: 0x7f090047
			public const int addPlayer = 2131296327;
			// aapt resource value: 0x7f090049
			public const int addPlayer = 2131296329;
			
			// aapt resource value: 0x7f090012
			public const int bonusText = 2131296274;
			
			// aapt resource value: 0x7f09002d
			public const int buttonFrameLayout = 2131296301;
			
			// aapt resource value: 0x7f090037
			public const int buttonLayout = 2131296311;
			
			// aapt resource value: 0x7f090005
			public const int cancelButton = 2131296261;
			
			// aapt resource value: 0x7f090041
			public const int changeCountScoreText = 2131296321;
			// aapt resource value: 0x7f090043
			public const int changeCountScoreText = 2131296323;
			
			// aapt resource value: 0x7f090003
			public const int chooseFromContButton = 2131296259;
			
			// aapt resource value: 0x7f090014
			public const int choosePhotoButton = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int choosePlayer = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int circle_crop = 2131296279;
			
			// aapt resource value: 0x7f09002f
			public const int completeGameButton = 2131296303;
			
			// aapt resource value: 0x7f090006
			public const int confirmButton = 2131296262;
			
			// aapt resource value: 0x7f09000f
			public const int congrats = 2131296271;
			
			// aapt resource value: 0x7f090020
			public const int contentFrameLayout = 2131296288;
			
			// aapt resource value: 0x7f090011
			public const int continueButton = 2131296273;
			
			// aapt resource value: 0x7f090043
			public const int currentScoreText = 2131296323;
			// aapt resource value: 0x7f090045
			public const int currentScoreText = 2131296325;
			
			// aapt resource value: 0x7f090046
			public const int customActionButton = 2131296326;
			// aapt resource value: 0x7f090048
			public const int customActionButton = 2131296328;
			
			// aapt resource value: 0x7f090040
			public const int descLayout = 2131296320;
			// aapt resource value: 0x7f090042
			public const int descLayout = 2131296322;
			
			// aapt resource value: 0x7f090008
			public const int doneImage = 2131296264;
			
			// aapt resource value: 0x7f090042
			public const int endDescriptionText = 2131296322;
			// aapt resource value: 0x7f090044
			public const int endDescriptionText = 2131296324;
			
			// aapt resource value: 0x7f09001c
			public const int imageBackgroundRules = 2131296284;
			
			// aapt resource value: 0x7f09003f
			public const int imageButOne = 2131296319;
			
			// aapt resource value: 0x7f090021
			public const int imageCardView = 2131296289;
			
			// aapt resource value: 0x7f09001f
			public const int imageScroll = 2131296287;
			
			// aapt resource value: 0x7f09000e
			public const int imageView = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int isPlayText = 2131296267;
			
			// aapt resource value: 0x7f090044
			public const int layout = 2131296324;
			// aapt resource value: 0x7f090046
			public const int layout = 2131296326;
			
			// aapt resource value: 0x7f090018
			public const int leadText = 2131296280;
			
			// aapt resource value: 0x7f09003d
			public const int light_bottom = 2131296317;
			// aapt resource value: 0x7f09003e
			public const int light_bottom = 2131296318;
			
			// aapt resource value: 0x7f09001b
			public const int linearLayout1 = 2131296283;
			
			// aapt resource value: 0x7f090023
			public const int logoImage = 2131296291;
			
			// aapt resource value: 0x7f090013
			public const int makePhotoButton = 2131296275;
			
			// aapt resource value: 0x7f090039
			public const int makeThisButton = 2131296313;
			
			// aapt resource value: 0x7f090001
			public const int playerImage = 2131296257;
			
			// aapt resource value: 0x7f090029
			public const int playerInGameImage = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int playerInGameName = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int playerInGamePostion = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int playerInGameScore = 2131296300;
			
			// aapt resource value: 0x7f090000
			public const int playerLayout = 2131296256;
			
			// aapt resource value: 0x7f090015
			public const int playerList = 2131296277;
			
			// aapt resource value: 0x7f090002
			public const int playerName = 2131296258;
			
			// aapt resource value: 0x7f09000a
			public const int playerNameLayout = 2131296266;
			
			// aapt resource value: 0x7f090028
			public const int playerPickList = 2131296296;
			
			// aapt resource value: 0x7f09001a
			public const int playerScore = 2131296282;
			
			// aapt resource value: 0x7f090031
			public const int playerTournamentListView = 2131296305;
			
			// aapt resource value: 0x7f09000d
			public const int playersList = 2131296269;
			
			// aapt resource value: 0x7f09003b
			public const int points = 2131296315;
			
			// aapt resource value: 0x7f090038
			public const int refuseButton = 2131296312;
			
			// aapt resource value: 0x7f09002e
			public const int relativeLayout = 2131296302;
			
			// aapt resource value: 0x7f090009
			public const int removeButton = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int removeLayout = 2131296263;
			
			// aapt resource value: 0x7f090034
			public const int scoreLayout = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int scoreString = 2131296309;
			
			// aapt resource value: 0x7f090019
			public const int scoreText = 2131296281;
			
			// aapt resource value: 0x7f090036
			public const int separator = 2131296310;
			
			// aapt resource value: 0x7f090030
			public const int shareButton = 2131296304;
			
			// aapt resource value: 0x7f090033
			public const int startGameLayout = 2131296307;
			
			// aapt resource value: 0x7f09000c
			public const int startPlayButton = 2131296268;
			
			// aapt resource value: 0x7f09003f
			public const int statusDescriptionText = 2131296319;
			// aapt resource value: 0x7f090041
			public const int statusDescriptionText = 2131296321;
			
			// aapt resource value: 0x7f09003e
			public const int statusTitleText = 2131296318;
			// aapt resource value: 0x7f090040
			public const int statusTitleText = 2131296320;
			
			// aapt resource value: 0x7f090048
			public const int tableButton = 2131296328;
			// aapt resource value: 0x7f09004a
			public const int tableButton = 2131296330;
			
			// aapt resource value: 0x7f09003d
			public const int tableShop = 2131296317;
			
			// aapt resource value: 0x7f09003a
			public const int taskImageButton = 2131296314;
			
			// aapt resource value: 0x7f090022
			public const int textCard = 2131296290;
			
			// aapt resource value: 0x7f09001e
			public const int textContainer = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int textHeader = 2131296285;
			
			// aapt resource value: 0x7f090045
			public const int titleText = 2131296325;
			// aapt resource value: 0x7f090047
			public const int titleText = 2131296327;
			
			// aapt resource value: 0x7f090032
			public const int viewPager = 2131296306;
			
			// aapt resource value: 0x7f09003c
			public const int x2 = 2131296316;
			
			// aapt resource value: 0x7f090010
			public const int youHaveBonus = 2131296272;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNewPlayer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddPlayerItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddPlayers = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Bonus = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChoosePhoto = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ChoosePlayer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ChoosePlayerItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FirstPlayerItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int FragmentOne = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int FragmentThree = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int FragmentTwo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ImageCard = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MainMenu = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PickPlayerDialog = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PlayerInGameItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PlayerItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ResultsGame = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Rules = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Splash = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int StartGame = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Store = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TaskStatus = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int YorshActionBar = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int YorshActionBarTournamentTable = 2130903063;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040012
			public const int AddNewPlayerLowCaseString = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int AddNewPlayerString = 2130968595;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04002a
			public const int AreYouLikeString = 2130968618;
			
			// aapt resource value: 0x7f040017
			public const int AreYouShureString = 2130968599;
			
			// aapt resource value: 0x7f040002
			public const int BoardGameString = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int BuyString = 2130968587;
			
			// aapt resource value: 0x7f040033
			public const int CancelString = 2130968627;
			
			// aapt resource value: 0x7f040011
			public const int ChooseFromContactString = 2130968593;
			
			// aapt resource value: 0x7f04001d
			public const int ChooseFromGalleryString = 2130968605;
			
			// aapt resource value: 0x7f040026
			public const int CompleteGameString = 2130968614;
			
			// aapt resource value: 0x7f040034
			public const int ConfirmString = 2130968628;
			
			// aapt resource value: 0x7f04002f
			public const int CongratString = 2130968623;
			
			// aapt resource value: 0x7f040021
			public const int ContinueString = 2130968609;
			
			// aapt resource value: 0x7f04002c
			public const int EasyString = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int EstimateUsString = 2130968619;
			
			// aapt resource value: 0x7f040016
			public const int GameString = 2130968598;
			
			// aapt resource value: 0x7f040006
			public const int GoToMosigraSite = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int IsNotPlayString = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int IsPlayString = 2130968589;
			
			// aapt resource value: 0x7f04002d
			public const int LaterString = 2130968621;
			
			// aapt resource value: 0x7f040023
			public const int LeadString = 2130968611;
			
			// aapt resource value: 0x7f040015
			public const int MakePhotoString = 2130968597;
			
			// aapt resource value: 0x7f04001a
			public const int MakeThisString = 2130968602;
			
			// aapt resource value: 0x7f040027
			public const int NewGameString = 2130968615;
			
			// aapt resource value: 0x7f04002e
			public const int NoFunString = 2130968622;
			
			// aapt resource value: 0x7f04000f
			public const int NoNameString = 2130968591;
			
			// aapt resource value: 0x7f040019
			public const int NoString = 2130968601;
			
			// aapt resource value: 0x7f040022
			public const int NotSupportCameraString = 2130968610;
			
			// aapt resource value: 0x7f040007
			public const int OpenSiteQuestionString = 2130968583;
			
			// aapt resource value: 0x7f040020
			public const int PickPlayerString = 2130968608;
			
			// aapt resource value: 0x7f040010
			public const int PlayerNameString = 2130968592;
			
			// aapt resource value: 0x7f04000c
			public const int PlayersString = 2130968588;
			
			// aapt resource value: 0x7f040031
			public const int PleaseSelectThePlayerString = 2130968625;
			
			// aapt resource value: 0x7f040005
			public const int PlusCardsString = 2130968581;
			
			// aapt resource value: 0x7f04001e
			public const int PositionPlayerString = 2130968606;
			
			// aapt resource value: 0x7f040032
			public const int PressReadyButtonString = 2130968626;
			
			// aapt resource value: 0x7f04001b
			public const int RefuseString = 2130968603;
			
			// aapt resource value: 0x7f040029
			public const int ResultsString = 2130968617;
			
			// aapt resource value: 0x7f04000a
			public const int RulesGameString = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int RulesString = 2130968580;
			
			// aapt resource value: 0x7f04001f
			public const int ScoreString = 2130968607;
			
			// aapt resource value: 0x7f040025
			public const int ScoresString = 2130968613;
			
			// aapt resource value: 0x7f040028
			public const int ShareString = 2130968616;
			
			// aapt resource value: 0x7f040014
			public const int StartGameButtonString = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int StartGameString = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int TheLongestBonusString = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int TheLongestTaskString = 2130968584;
			
			// aapt resource value: 0x7f04001c
			public const int TournirTableString = 2130968604;
			
			// aapt resource value: 0x7f040024
			public const int WinnerString = 2130968612;
			
			// aapt resource value: 0x7f040018
			public const int YesString = 2130968600;
			
			// aapt resource value: 0x7f040030
			public const int YouHaveBonusString = 2130968624;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int Theme_AppTheme = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Theme_WithoutActionBar = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int WhiteActionBar = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int YourshDialog = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
